server:
  port: 8011

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shoven1/springcloud
  rabbitmq:
    host: ${rabbitmq.host}
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaServer:8001/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 192.168.0.147
management:
  endpoints:
    web:
      exposure:
        include: "*"
