server:
  port: 8011

spring:
  application:
    name: config-server
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shoven1/springcloud
  rabbitmq:
    host: ${rabbitmq.host}
    port: 5672
    username: guest
    password: guest


management:
  endpoints:
    web:
      exposure:
        include: "*"

---

spring:
  profiles: dev

eureka:
  instance:
    hostname: ${spring.application.name}
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/

---

spring:
  profiles: config-server1

eureka:
  instance:
    hostname: ${spring.profiles}
  client:
    service-url:
      defaultZone: http://eureka-server1:8001/eureka/

---

spring:
  profiles: config-server2

eureka:
  instance:
    hostname: ${spring.profiles}
  client:
    service-url:
      defaultZone: http://eureka-server2:8001/eureka/

---

spring:
  profiles: config-server3

eureka:
  instance:
    hostname: ${spring.profiles}
  client:
    service-url:
      defaultZone: http://eureka-server3:8001/eureka/

---
