version: '3'

services:
  eurekaServer:
    image: eureka:latest
    command: &address ["--rabbitmq.host=192.168.0.147"]
    expose:
      - 8001
    ports:
      - 8001:8001
  configServer:
    image: config:latest
    expose:
      - 8011
    ports:
      - 8011:8011
    command: *address
    links:
      - eurekaServer
  gateway:
    image: gateway:latest
    expose:
      - 8021
    ports:
      - 80:8021
    command: &address2 ["--rabbitmq.host=192.168.0.147", "--eurekaServer.host=192.168.0.147"]
    links:
      - client1
  client1:
    image: client1:latest
    command: *address2
    expose:
      - 8081
