version: '3'

services:
  gateway:
    image: gateway:latest
    ports:
      - 80:8021
    networks:
      - cloud-net
    environment:
      - spring.profiles.active=prod
      - &rabbitmqHost rabbitmq.ip=192.168.0.147
      - eurekaServer.host=192.168.0.147:8001
  client1:
    image: client1:latest
    networks:
      - cloud-net
    environment:
      - spring.profiles.active=prod
      - *rabbitmqHost
