version: '3'
#  properties:
#    - &rabbitmqAddress "--rabbitmq.address=192.168.0.147"
#    - &mysqlAddress "--rabbitmq.address=192.168.0.147"
services:
  eurekaServer:
    image: eureka:latest
    command: &address ["--rabbitmq.address=192.168.0.147"]
    expose:
      - 8001
    ports:
      - 8001:8001
  configServer:
    image: config:latest
    expose:
      - 8011
    ports:
      - 8011:8011
    command: *address
    links:
      - eurekaServer
    depends_on:
      - eurekaServer
