server:
  port: 8021

spring:
  rabbitmq:
    host: ${rabbitmq.host}
    port: 5672
    username: guest
    password: guest

zuul:
  routes:
    client:
      path: /api/**
      serviceId: client



