server:
  port: 8001

spring:
  rabbitmq:
    host: ${rabbitmq.address}
    port: 5672
    username: guest
    password: guest

eureka:
  server:
    # 关闭保护机制 生产环境建议开启
    enable-self-preservation: false
  instance:
    hostname: localhost
  client:
    #由于该应用为注册中心,设置为false,表明不向注册中心注册自己
    register-with-eureka: false
    #是否从eureka服务器获取注册信息，这里不需要
    fetch-registry: false
    service-url:
      defaultZon e: http://${eureka.instance.hostname}:${server.port}/eureka/
